{"name": "test_rerun_1", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = choice([True, False])\n +    where choice = random.choice", "trace": "self = <tests.pytest.test_reruns.TestReruns object at 0x10cd47920>\n\n    def test_rerun_1(self):\n>       assert random.choice([True, False])\nE       assert False\nE        +  where False = choice([True, False])\nE        +    where choice = random.choice\n\ntests/pytest/test_reruns.py:16: AssertionError"}, "start": 1751216056405, "stop": 1751216056405, "uuid": "d4e361c3-c690-4f14-b85f-157d79e258be", "historyId": "81d6ff8066b3db2379029adbb835c586", "testCaseId": "81d6ff8066b3db2379029adbb835c586", "fullName": "tests.pytest.test_reruns.TestReruns#test_rerun_1", "labels": [{"name": "parentSuite", "value": "tests.pytest"}, {"name": "suite", "value": "test_reruns"}, {"name": "subSuite", "value": "TestReruns"}, {"name": "host", "value": "MacBook-Pro-Tochka-2.local"}, {"name": "thread", "value": "79947-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.pytest.test_reruns"}]}